# Generated by Django 2.1.3 on 2018-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailFormItem', models.EmailField(blank=True, max_length=70)),
                ('modelFormItem', models.CharField(choices=[('1', 'COMB'), ('2', 'CP'), ('3', 'TIS')], default=None, max_length=1)),
                ('bypassSignalPepFormItem', models.BooleanField(choices=[(True, 'signalPeptideBypassFormItem'), (False, 'NotsignalPeptideBypassFormItem')], default=False)),
                ('sORFSequenceFormItem', models.CharField(max_length=255)),
                ('fileNameFormItem', models.FileField(upload_to='uploadedFiles/')),
                ('ATGStartingPosFormItem', models.IntegerField()),
                ('simulateLength', models.IntegerField()),
            ],
        ),
    ]
