# Generated by Django 2.1.2 on 2018-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20181115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='bypassSignalPepFormItem',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='fileNameFormItem',
            field=models.FileField(blank=True, upload_to='./%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='inputTypeFormItem',
            field=models.BooleanField(choices=[(True, 'Sequence'), (False, 'File')], default=True),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='sORFSequenceFormItem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='simulateLength',
            field=models.IntegerField(blank=True),
        ),
    ]
