# Generated by Django 2.1.2 on 2018-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20181115_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='simulateLength',
            field=models.IntegerField(),
        ),
    ]
