# Generated by Django 2.1.2 on 2018-11-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20181115_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='simulateLength',
            field=models.IntegerField(blank=True),
        ),
    ]
